name: build
on: 
  push:
    branches: [master]
  paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [master]

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1 
    - uses: actions/setup-java@v1
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable' 
    - run: flutter pub get
    - run: flutter analyze
    - run: flutter test